config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :all
  devise_scope :user do
    get '/users/sign_in' => 'devise/sessions#new', as: :new_user_session
    post '/users/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "articles#index"

  resources :articles

  resources :about_me, only: %i[index]

  resources :inquiries, only: %i[index new create show]

  get '*path', controller: 'application', action: 'render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image
  validates :title, :content, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  validates :title, length: { maximum: 150 }
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  def index
    render layout: 'about_me'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

rescue_from ActiveRecord::RecordNotFound, with: :render_404
rescue_from ActionController::RoutingError, with: :render_404

def render_404
  render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  layout 'header_and_main'

  def index
    @inquiries = Inquiry.all
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)

    if @inquiry.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  private
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :title, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0]

      case language.to_s
      when 'ruby'
          lang = 'ruby'
      when 'yml'
          lang = 'yaml'
      when 'css'
          lang = 'css'
      when 'html'
          lang = 'html'
      when ''
          lang = 'md'
      else
          lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/about_me/index.html.haml
#app
  %h1#ityped.main__title.col-12.text-center.mb-5
  .container
    .row.scroll_animation.scroll_up
      .menu__list.col-12.d-flex.text-center.my-5
        %a.menu.col-2.text-center{:href => "#profile"} Profile
        %a.menu.col-2.text-center{:href => "#portfolio"} Portfolio
        %a.menu.col-2.text-center{:href => "#blog"} Blog
        %a.menu.col-2.text-center{:href => "#skill"} Skill
        %a.menu.col-2.text-center{:href => "https://github.com/gangelion", :target => "_blank"} Github
        %a.menu.col-2.text-center{:href => "#contact"} Contact
    .row.scroll_animation.scroll_up
      %h2#profile.profile.col-12.text-center.my-5 Profile
      .d-flex.col-12
        .profile__content.col-6
          1991年5月29日生まれ 東京都出身。
          %br>/
          趣味は
          %br>/
          ・英語学習（毎日オンライン英会話を継続中）
          %br>/
          ・読書（年間150冊読んだことも。最近は技術本を読み漁る）
          %br>/
          ・旅行（海外旅行が好き、アメリカ、インドネシア、ペルーなど）
          %br>/
          ・筋トレ（過去にベストボディジャパンに出場した経験あり）
          %br>/
          2015~2019 東京消防庁消防官
          %br>/
          2019~ エンジニアへ
          .sns.mt-5
            %a{:href => "https://twitter.com/tetsuyakojima86", :target => "_blank"}
              %i.fab.fa-twitter-square.mx-2
            %a{:href => "https://www.facebook.com/profile.php?id=100015453796123", :target => "_blank"}
              %i.fab.fa-facebook-square.mx-2
            %a{:href => "https://github.com/gangelion", :target => "_blank"}
              %i.fab.fa-github-square.mx-2
        .col-6.d-flex.justify-content-center
          %img.profile__image{:alt => "プロフィール画像", :src => "assets/T1MLERC4C-UR31TJGLT-bffc2f115b74-512.jpg"}/
    .row.scroll_animation.scroll_up
      %h2#portfolio.portfolio.col-12.text-center.my-5 Portfolio
      %h3.col-12.text-center.mb-5
        firstskillapp
        %a.portfolio__link{:href => "https://firstskillapp.com", :target => "_blank"} https://firstskillapp.com
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-18-178-33-110-2020-03-27-11_45_19.png"}/
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-18-178-33-110-users-2020-03-27-11_47_18.png"}/
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-localhost-3000-plans-new-2020-03-22-23_00_51.png"}/
    .row.scroll_animation.scroll_up
      %h2#blog.blog.col-12.text-center.my-5 Blog
      .blog__list.col-12.d-flex.text-center
        .article.col-6 ブログ記事1
        .article.col-6 ブログ記事2
      .col-12.text-center
        = link_to "ブログ一覧へ", articles_path
    .row.scroll_animation.scroll_up
      %h2#skill.skill.col-12.text-center.my-5 Skill
      .skill__list
        %div
          Ruby on Rails
          %i.fas.fa-star
        %div
          Laravel
          %i.fas.fa-star-half
        %div
          JavaScript
          %i.fas.fa-star
        %div
          Vue.js
          %i.fas.fa-star
        %div
          JQuery
          %i.fas.fa-star-half
        %div
          Docker
          %i.fas.fa-star
        %div
          CircleCI
          %i.fas.fa-star-half
        %div
          AWS
          %i.fas.fa-star
  %v-move-to-top.move_to_top_icon
:javascript
  Vue.component('v-move-to-top', {
    data() {
      return {
        show: false
      };
    },
    template: `<transition name="fade">
                <i class="fas fa-arrow-circle-up" v-if="show" @click="moveToTop"></i>
              </transition>`,
              mounted() {
                window.addEventListener('scroll', () => {
                  this.show = (window.scrollY > 150);
                });
              },
    methods: {
      moveToTop() {
        const duration = 300;
        const interval = 30;
        const step = -window.scrollY / Math.ceil(duration / interval);
        const timer = setInterval(() => {
          window.scrollBy(0, step);
          if(window.scrollY <= 0) {
            clearInterval(timer);
          }
        }, interval);
      }
    }
  });

  new Vue({
    el: '#app'
  });

app/views/articles/_right_content.html.haml
.col-3
  .profile__box.bg-white.shadow-sm
    = image_tag "T1MLERC4C-UR31TJGLT-bffc2f115b74-512.jpg", class: "profile__box_image"
    .col-12.text-center.mt-2.mb-4
      サイト運営者 小島徹也
    .profile__box_content.text-wrap.text-break
      28歳で消防官を退職し全くの異業種であるエンジニアへ
      %br 物づくりの楽しさに目覚め転職を決意
      %br (このサイトも0から自分で全て作っています。)
      %br 役立つ情報を発信していきます。
      %br 趣味は読書と英会話
      %br 好きな言葉はgive&give
      %br サイトのご意見ご感想も気軽に受け付けております。
      .pb-3
        = link_to "サイト運営者についてもっと詳しく", about_me_index_path

app/views/articles/edit.html.haml
= render partial: "layouts/form"

app/views/articles/index.html.haml
.container
  .row
    .col-12.my-5
      .col-12
        = link_to "Qiita", "https://qiita.com/tetsuyakojima"
      - if user_signed_in?
        .col-12
          = link_to "記事を投稿する", new_article_path
        .col-12
          = link_to "お問合せ確認", inquiries_path
      .col-12.d-flex
        .col-9
          - @articles.each do |article|
            .bg-white.shadow.d-flex.my-3.p-3
              = link_to image_tag(article.image, class: "article__image"), article_path(article)
              .text
                .article__title.text-wrap.text-break.px-2
                  = link_to article.title, article_path(article)
                .article__content.text-wrap.text-break.px-2
                  = link_to article.content, article_path(article)
        = render 'right_content'

app/views/articles/new.html.haml
= render partial: "layouts/form"

app/views/articles/show.html.haml
.container
  .row
    .col-12.d-flex.my-5
      .show__content.col-9.bg-white.shadow-sm
        .col-12.text-right.mt-3
          - if user_signed_in?
            %i.fas.fa-edit
              = link_to "記事を編集する", edit_article_path
            %i.fas.fa-trash
              = link_to "記事を削除する", article_path, method: :delete, data: {confirm: "削除します。よろしいですか？"}
        .py-3
          = image_tag(@article.image, class: "article__top_image")
        .h2.my-5
          = @article.title
        .col-12.mt-5.text-wrap.text-break
          = markdown(@article.content).html_safe
      = render 'right_content'

app/views/inquiries/index.html.haml
.container
  .row
    .col-12
      = "#{@inquiries&.length}件のお問い合わせが届いています。"
    .col-12
      - @inquiries&.each do |inquiry|
        .inquiry__box.bg-white.text-break
          .col-12.mt-3 名前
          = link_to inquiry.name, inquiry_path(inquiry)
          .col-12.mt-3 メールアドレス
          = inquiry.email
          .col-12.mt-3 タイトル
          = inquiry.title
          .col-12.mt-3 メッセージ
          = inquiry.message

app/views/inquiries/new.html.haml
.container
  .row
    .col-12
      = form_with model: @inquiry, local: true do |f|
        .col-12.h3.my-5.text-center お問い合わせフォーム
        = render 'layouts/error_messages', model: f.object
        .d-flex
          .mt-3 お名前
          .mt-3.required (必須)
        = f.text_field :name, class: "form-control", required: true, maxlength: 30
        .d-flex
          .mt-3 メールアドレス
          .mt-3.required (必須)
        = f.email_field :email, class: "form-control", required: true
        .mt-3 件名
        = f.text_field :title, class: "form-control", maxlength: 150
        .d-flex
          .mt-3 お問合わせ内容
          .mt-3.required (必須)
        = f.text_area :message, class: "form-control mb-5", rows: 10, required: true
        .col-12.text-center
          = f.submit "送信する", data: {confirm: "送信します。よろしいですか？"}, class: "btn btn-info mb-5"

app/views/inquiries/show.html.haml
.container
  .row
    .col-12
      .inquiry__box.bg-white.text-break.shadow-sm
        .col-12.mt-3 名前
        = @inquiry.name
        .col-12.mt-3 メールアドレス
        = @inquiry.email
        .col-12.mt-3 タイトル
        = @inquiry.title
        .col-12.mt-3 メッセージ
        = @inquiry.message
    = link_to "お問い合わせ一覧に戻る", inquiries_path, class: "my-3"

app/views/layouts/_error_messages.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li
          = message

app/views/layouts/_footer.html.haml
%footer.bg-white
  .container
    .row
      .col-6.h3.my-3.text-center Contact
      .col-12.d-flex
        .col-6.text-center.my-3
          = link_to 'お問い合わせフォームへ', new_inquiry_path
        .col-6
          .col-12.d-flex.justify-content-end
            = link_to "管理者用ログインページ", new_user_session_path
          .col-12.d-flex.justify-content-end
            - if user_signed_in?
              = link_to "ログアウト", destroy_user_session_path, method: :delete
      .col-12.text-center
        %small.col-12 © 2020 Kojima's Garage

app/views/layouts/_form.html.haml
#app
  = form_with model: @article, local: true do |f|
    .col-12.my-3
      = f.text_field :title, class: "form-control", placeholder: "タイトル"
    .col-12.my-3
      = f.file_field :image
    .col-12.d-flex
      .col-6.my-3
        = f.text_area :content, class: "form-control", "@input" => "update", "@dragenter" => "dragEnter", "@dragleave" => "dragLeave", "@drop.prevent" => "dropFile", ":class" => "{enter: isEnter}", rows: 33, placeholder: "本文"
      .form__textarea.col-6.my-3.form-control.text-wrap.text-break
        %div{ "v-html" => "compiledMarkdown" }
    .col-12
      = f.submit "投稿する", data: {confirm: "投稿します。よろしいですか？"}, class: "form__btn btn btn-info"

%script{src: "http://cdnjs.cloudflare.com/ajax/libs/marked/0.3.2/marked.min.js"}
%script{src: "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"}
:javascript
  new Vue({
    el: "#app",
    data: {
      input: "",
      isEnter: false,
      filse: []
    },
    computed: {
      compiledMarkdown: function () {
        return  marked(this.input, {
          sanitize: true,
          breaks: true,
        })
      }
    },
    methods: {
      update: _.debounce(function (e) {
        this.input = e.target.value
      }, 300),
      dragEnter() {
        this.isEnter = true;
      },
      dragLeave() {
        this.isEnter = false;
      },
      dropFile(e) {
        this.files = [...e.dataTransfer.files]
        this.isEnter = false;
      }
    }
  })

app/views/layouts/about_me.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyHomePage
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application', 'about_me/index'
  %body.bg-light
    %main
      %script{:src => "https://cdn.jsdelivr.net/npm/vue/dist/vue.js"}
      = yield
    = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyHomePage
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    %script{src: "https://cdn.jsdelivr.net/npm/vue/dist/vue.js"}
  %body.bg-light
    %header.bg-info
      .header__title
        = link_to "Kojima's Garage", articles_path
    %main
      = yield
    = render 'layouts/footer'

app/views/layouts/header_and_main.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyHomePage
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body.bg-light
    %header.bg-info
      .header__title
        = link_to "Kojima's Garage", articles_path
    %main
      = yield

app/views/top_pages/index.html.haml
#app
  %h1.main__title.col-12.text-center.mb-5 Hello,World!
  .container
    .row
      .menu__list.col-12.d-flex.text-center.my-5
        %a.menu.col-2.text-center{:href => "#profile"} Profile
        %a.menu.col-2.text-center{:href => "#portfolio"} Portfolio
        %a.menu.col-2.text-center{:href => "#blog"} Blog
        %a.menu.col-2.text-center{:href => "#skill"} Skill
        %a.menu.col-2.text-center{:href => "https://github.com/gangelion", :target => "_blank"} Github
        %a.menu.col-2.text-center{:href => "#contact"} Contact
    .row
      %h2#profile.profile.col-12.text-center.my-5 Profile
      .d-flex.col-12
        .profile__content.col-6
          1991年5月29日生まれ 東京都出身。
          %br>/
          趣味は
          %br>/
          ・英語学習（毎日オンライン英会話を継続中）
          %br>/
          ・読書（年間150冊読んだことも。最近は技術本を読み漁る）
          %br>/
          ・旅行（海外旅行が好き、アメリカ、インドネシア、ペルーなど）
          %br>/
          ・筋トレ（過去にベストボディジャパンに出場した経験あり）
          %br>/
          2015~2019 東京消防庁消防官
          %br>/
          2019~ エンジニアへ
          .sns.mt-5
            %a{:href => "https://twitter.com/tetsuyakojima86", :target => "_blank"}
              %i.fab.fa-twitter-square.mx-2
            %a{:href => "https://www.facebook.com/profile.php?id=100015453796123", :target => "_blank"}
              %i.fab.fa-facebook-square.mx-2
            %a{:href => "https://github.com/gangelion", :target => "_blank"}
              %i.fab.fa-github-square.mx-2
        .col-6.d-flex.justify-content-center
          %img.profile__image{:alt => "プロフィール画像", :src => "assets/T1MLERC4C-UR31TJGLT-bffc2f115b74-512.jpg"}/
    .row
      %h2#portfolio.portfolio.col-12.text-center.my-5 Portfolio
      %h3.col-12.text-center.mb-5
        firstskillapp
        %a.portfolio__link{:href => "https://firstskillapp.com", :target => "_blank"} https://firstskillapp.com
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-18-178-33-110-2020-03-27-11_45_19.png"}/
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-18-178-33-110-users-2020-03-27-11_47_18.png"}/
      %img.col-4{:alt => "ポートフォリオ", :src => "assets/screencapture-localhost-3000-plans-new-2020-03-22-23_00_51.png"}/
    .row
      %h2#blog.blog.col-12.text-center.my-5 Blog
      .blog__list.col-12.d-flex.text-center
        .article.col-6 ブログ記事1
        .article.col-6 ブログ記事2
      .col-12.text-center
        = link_to "ブログ一覧へ", articles_path
    .row
      %h2#skill.skill.col-12.text-center.my-5 Skill
      .skill__list
        %div
          Ruby on Rails
          %i.fas.fa-star
        %div
          Laravel
          %i.fas.fa-star-half
        %div
          JQuery
          %i.fas.fa-star-half
        %div
          Docker
          %i.fas.fa-star
        %div
          CircleCI
          %i.fas.fa-star-half
        %div
          AWS
          %i.fas.fa-star
  %v-move-to-top.move_to_top_icon
:javascript
  Vue.component('v-move-to-top', {
    data() {
      return {
        show: false
      };
    },
    template: `<transition name="fade">
                <i class="fas fa-arrow-circle-up" v-if="show" @click="moveToTop"></i>
              </transition>`,
              mounted() {
                window.addEventListener('scroll', () => {
                  this.show = (window.scrollY > 150);
                });
              },
    methods: {
      moveToTop() {
        const duration = 300;
        const interval = 30;
        const step = -window.scrollY / Math.ceil(duration / interval);
        const timer = setInterval(() => {
          window.scrollBy(0, step);
          if(window.scrollY <= 0) {
            clearInterval(timer);
          }
        }, interval);
      }
    }
  });

  new Vue({
    el: '#app'
  });